#!/bin/python3

'''
This script runs the COmmunity SWAT+ Model
(CoSWAT-Global) one by one.

Author  : Celray James CHAWANDA
Date    : 14/07/2022
Contact : celray@chawanda.com
Licence : MIT
GitHub  : github.com/celray
'''

import os, sys, platform, argparse, subprocess, threading, time, pty
from cjfx import list_all_files, exists, write_to, read_from, ignore_warnings, list_folders, format_timedelta, show_progress
from coswatFX import runSWATPlus, resolveRegions
from collections import defaultdict
from datetime import datetime, timedelta

ignore_warnings()

# change working directory
me = os.path.realpath(__file__)
os.chdir(os.path.dirname(me))

import datavariables as variables
from resources.print_file import print_prt
import json as jsonmod


def convertOutletToRecall(srcFile, dstFile, recName):
    """Convert object.prt daily output to recall.rec data file format.
    flo: m3/s -> m3 (x86400), null column -> tmp, column names adjusted."""
    with open(srcFile, 'r') as f:
        lines = f.readlines()

    if len(lines) < 2:
        return False

    dataRows = []
    for line in lines[1:]:
        parts = line.split()
        if len(parts) < 24: continue

        jday   = int(parts[0])
        mo     = int(parts[1])
        day_mo = int(parts[2])
        yr     = int(parts[3])
        flo    = float(parts[6]) * 86400   # m3/s -> m3/day
        vals   = [float(parts[i]) for i in range(7, 23)]   # sed through grv
        tmp    = float(parts[23]) if len(parts) > 23 else 0.0  # temperature from null column

        dataRows.append((jday, mo, day_mo, yr, flo, *vals, tmp))

    with open(dstFile, 'w') as f:
        f.write(f'recall data: generated by CoSWAT for subregion routing\n')
        f.write(f'{len(dataRows)}\n')
        headers = ['jday','mo','day_mo','yr','ob_typ','ob_name',
                   'flo','sed','orgn','sedp','no3','solp','chla','nh3','no2','cbod','dox',
                   'san','sil','cla','sag','lag','grv','tmp']
        f.write(''.join(f'{h:>16}' for h in headers) + '\n')

        for row in dataRows:
            jday, mo, day_mo, yr, flo, *rest = row
            f.write(f'{jday:16d}{mo:16d}{day_mo:16d}{yr:16d}')
            f.write(f'{"pt_day":>16}')
            f.write(f'{recName:>16}')
            f.write(f'{flo:16.7E}')
            for v in rest:
                f.write(f'{v:16.7E}')
            f.write('\n')

    return True


def doRecallConversion(subDir, schemaData, allSubs, modelSetupBase, region, version):
    """After upstream finishes, convert its outlet output to recall for downstream."""
    mappings = schemaData.get('channelMappings', {})
    srId     = subDir.split('-')[0]
    simDir   = os.path.abspath(f'../simulations/CoSWATv{version}/{region}/{subDir}')
    txtDir   = f"{modelSetupBase}/{region}/{subDir}/Scenarios/Default/TxtInOut"

    for connKey, mapping in mappings.items():
        if subDir not in mapping or mapping[subDir]['role'] != 'outlet': continue

        channelNum = mapping[subDir]['channel']
        fromSub    = connKey.split('->')[0]
        toSub      = connKey.split('->')[1]
        outFile    = f'{srId}_to_{toSub}_ch{channelNum}.txt'
        recName    = f'inlet_from_{fromSub}'

        # check simulations first, fallback to TxtInOut
        srcFile = f'{simDir}/{outFile}'
        if not exists(srcFile): srcFile = f'{txtDir}/{outFile}'
        if not exists(srcFile): continue

        toSubDir = next((s for s in allSubs if s.split('-')[0] == toSub), None)
        if toSubDir is None: continue
        dstFile = f"{modelSetupBase}/{region}/{toSubDir}/Scenarios/Default/TxtInOut/{recName}.rec"

        convertOutletToRecall(srcFile, dstFile, recName)


def swatWorker(subDir, txtDir, yr_fro, yr_to, executable_path, progressState, lock):
    """Run SWAT+ in a thread, updating shared progressState. Uses cwd instead of os.chdir."""
    write_to(f"{txtDir}/time.sim", f"time.sim: written by CoSWAT Data Writer\nday_start  yrc_start   day_end   yrc_end      step  \n       0      {yr_fro}         0      {yr_to}         0  ")
    write_to(f"{txtDir}/print.prt", print_prt)

    if not exists(f"{txtDir}/file.cio"):
        with lock:
            progressState[subDir] = {'status': 'error', 'msg': 'no file.cio'}
        return False

    yr_from_int = int(yr_fro)
    yr_to_int   = int(yr_to)
    numDays     = (datetime(yr_to_int, 12, 31) - datetime(yr_from_int, 1, 1)).days + 1

    with lock:
        progressState[subDir] = {'status': 'running', 'current': 0, 'total': numDays, 'date': '', 'eta': ''}

    # use pty to force line-buffered stdout from statically-linked Fortran binary
    master_fd, slave_fd = pty.openpty()
    process = subprocess.Popen(executable_path, stdout=slave_fd, stderr=slave_fd, cwd=txtDir)
    os.close(slave_fd)

    current       = 0
    day_cycle     = []
    previous_time = None
    buffer        = ''

    while True:
        try:
            data = os.read(master_fd, 4096)
            if not data: break
            buffer += data.decode('utf-8', errors='replace')
        except OSError:
            break

        while '\n' in buffer:
            line, buffer = buffer.split('\n', 1)
            line_parts = line.strip().split()

            if 'Simulation' in line_parts:
                ref = line_parts.index('Simulation')
                try:
                    year  = line_parts[ref + 3]
                    month = line_parts[ref + 1]
                    day   = line_parts[ref + 2]
                except IndexError:
                    continue

                month = f"0{month}" if int(month) < 10 else month
                day   = f"0{day}"   if int(day) < 10   else day

                current += 1

                if previous_time is not None:
                    day_cycle.append(datetime.now() - previous_time)

                eta_str = ''
                if len(day_cycle) > 40:
                    if len(day_cycle) > int(7 * 365.25): del day_cycle[0]
                    av = sum(day_cycle, timedelta()) / len(day_cycle)
                    eta_str = format_timedelta(av * (numDays - current))

                with lock:
                    progressState[subDir] = {
                        'status':  'running',
                        'current': current,
                        'total':   numDays,
                        'date':    f'{day}/{month}/{year}',
                        'eta':     eta_str
                    }

                previous_time = datetime.now()

    os.close(master_fd)
    process.wait()
    with lock:
        progressState[subDir] = {'status': 'done'}

    return True


def renderBars(allSubs, progressState, subDeps, lock, numLines):
    """Render multi-line progress bars using ANSI escape codes."""
    if numLines > 0:
        sys.stdout.write(f'\033[{numLines}A')

    # sort: running/done first, waiting last
    running = [s for s in allSubs if progressState.get(s, {}).get('status') in ('running', 'done', 'error', 'starting')]
    waiting = [s for s in allSubs if s not in running]
    ordered = running + waiting

    termWidth = 100
    try: termWidth = os.get_terminal_size(0)[0]
    except: pass

    with lock:
        for sub in ordered:
            s      = progressState.get(sub, {})
            status = s.get('status', 'queued')
            label  = sub

            if status == 'done':
                bar  = '█' * 15
                line = f'  {label:<22} [{bar}] done'
            elif status == 'running':
                current = s.get('current', 0)
                total   = s.get('total', 1)
                pct     = current / total if total > 0 else 0
                filled  = int(15 * pct)
                bar     = '█' * filled + '░' * (15 - filled)
                date_s  = s.get('date', '')
                eta_s   = s.get('eta', '')
                eta_show = f' ETA-{eta_s}' if eta_s else ''
                line = f'  {label:<22} [{bar}] {pct*100:5.1f}%  >> {date_s}{eta_show}'
            elif status == 'waiting':
                deps = s.get('deps', '')
                line = f'  {label:<22} waiting for sr {deps}'
            elif status == 'error':
                line = f'  {label:<22} ! {s.get("msg", "error")}'
            elif status == 'starting':
                line = f'  {label:<22} starting...'
            else:
                line = f'  {label:<22} queued'

            sys.stdout.write(f'\r{line:<{termWidth}}\n')

    sys.stdout.flush()
    return len(ordered)


def runSubregionsParallel(allSubs, subDeps, schemaData, modelSetupBase, region, version, yr_fro, yr_to, executable_path, maxWorkers):
    """Run subregions in parallel with dependency-aware scheduling and multi-progress bars."""
    lock          = threading.Lock()
    progressState = {}
    completed     = set()
    running       = {}      # {thread: subDir}
    numLines      = 0

    # init waiting states
    for sub in allSubs:
        deps = subDeps.get(sub, set()) - completed
        if deps:
            depIds = ', '.join(sorted(d.split('-')[0] for d in deps))
            progressState[sub] = {'status': 'waiting', 'deps': depIds}
        else:
            progressState[sub] = {'status': 'queued'}

    print(f'\n# running SWAT+ for {region} ({len(allSubs)} subregions, {maxWorkers} parallel)\n')
    numLines = renderBars(allSubs, progressState, subDeps, lock, 0)

    while len(completed) < len(allSubs):
        # start ready subregions (up to maxWorkers)
        for sub in allSubs:
            if sub in completed or sub in running.values(): continue
            if not subDeps[sub].issubset(completed): continue
            if len(running) >= maxWorkers: break

            txtDir = f"{modelSetupBase}/{region}/{sub}/Scenarios/Default/TxtInOut"
            with lock:
                progressState[sub] = {'status': 'starting'}

            t = threading.Thread(target=swatWorker, args=(sub, txtDir, yr_fro, yr_to, executable_path, progressState, lock))
            t.start()
            running[t] = sub

        # check for finished threads
        finished = [t for t in running if not t.is_alive()]
        for t in finished:
            subDir = running.pop(t)
            t.join()
            completed.add(subDir)

            # convert outlet output to recall for downstream
            doRecallConversion(subDir, schemaData, allSubs, modelSetupBase, region, version)

            # update waiting deps display
            with lock:
                for sub in allSubs:
                    if sub in completed or sub in running.values(): continue
                    remaining = subDeps[sub] - completed
                    if remaining:
                        depIds = ', '.join(sorted(d.split('-')[0] for d in remaining))
                        progressState[sub] = {'status': 'waiting', 'deps': depIds}
                    elif progressState.get(sub, {}).get('status') == 'waiting':
                        progressState[sub] = {'status': 'queued'}

        numLines = renderBars(allSubs, progressState, subDeps, lock, numLines)
        time.sleep(0.2)

    print(f'\n  > all subregions complete for {region}\n')


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="a script for running the model setup and delineation.")

    parser.add_argument("r", help="the name of the region to run the model for. If not specified, all regions will be processed.", nargs='*', default=[])
    parser.add_argument("--v", help="the version of the model setup to use. If not specified, the datavariables value will be used.", nargs='?', default=None)
    parser.add_argument("--sr", help="subregion id(s) to run", nargs='*', default=None)
    parser.add_argument("--y", help="the years to run the model for. If not specified, the datavariables value will be used.", nargs='?', default=None)

    args = parser.parse_args()

    # get years
    if args.y is None: years = variables.run_period
    else: years = args.y
    yr_fro, yr_to = years.split("-")

    # get model setup version
    if args.v is None: version = variables.version
    else: version = args.v

    if not exists(f"../model-setup/CoSWATv{version}"):
        print(f'\t! the version, CoSWATv{version}, does not exist, the following versions are available:')
        for v in list_folders('../model-setup/'):
            if v.startswith('CoSWATv'):
                print(f'\t\t- {v}')
        print(f'\t> please specify a valid version using the --v argument')
        sys.exit(1)

    # get regions
    if len(args.r) > 0: regions = resolveRegions(args.r)
    else: regions = list_folders(f"../model-setup/CoSWATv{version}/")

    modelSetupBase = os.path.abspath(f'../model-setup/CoSWATv{version}')

    for region in regions:
        schemaFn = f'{modelSetupBase}/{region}/schema.json'

        # non-subregioned region: run single model
        if not exists(schemaFn):
            txtDir = f"{modelSetupBase}/{region}/Scenarios/Default/TxtInOut"
            write_to(f"{txtDir}/time.sim", f"time.sim: written by CoSWAT Data Writer\nday_start  yrc_start   day_end   yrc_end      step  \n       0      {yr_fro}         0      {yr_to}         0  ")
            write_to(f"{txtDir}/print.prt", print_prt)
            if exists(f"{txtDir}/file.cio"):
                print(f"\n\n# running SWAT+ for {region}")
                runSWATPlus(txtDir, executable_path = variables.executable_path, modelName = region)
            else:
                print(f"\n\n! cannot run SWAT+ for {region}")
            continue

        with open(schemaFn, 'r') as f:
            schemaData = jsonmod.load(f)

        allSubs     = schemaData['subregions']
        connections = schemaData.get('connections', [])

        # filter by --sr if specified
        if args.sr is not None:
            allSubs = [s for s in allSubs if s.split('-')[0] in args.sr]

        # build dependency graph
        subDeps = defaultdict(set)
        for conn in connections:
            fromDir = conn['from']
            toDir   = conn['to']
            if fromDir in allSubs and toDir in allSubs:
                subDeps[toDir].add(fromDir)

        maxWorkers = min(variables.subregionProcesses, len(allSubs))

        runSubregionsParallel(allSubs, subDeps, schemaData, modelSetupBase,
                              region, version, yr_fro, yr_to,
                              variables.executable_path, maxWorkers)
